stages:
  - QA
  - buildImage
  - deployImage

buildImage:
  stage: buildImage
  before_script:
    - docker login -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD} ${REGISTRY}
  script:
    - docker build -t ${REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_BRANCH} .
    - docker push ${REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_BRANCH}
  only:
    - nefertiti-development
    - nefertiti-testing
    - nefertiti-staging

deployNefStagingFailover:
  stage: deployImage
  beforer_script: 
    - cat ${NEF_DEVELOPMENT_KEY} > ~/${NEF_DEVELOPMENT_KEY}
    - chmod a+x ~/${NEF_DEVELOPMENT_KEY}
  script:
    - ssh -i ~/${NEF_DEVELOPMENT_KEY} ${NEF_DEVELOPMENT_IP} "cd /home/master/nef-development/ && docker-compose pull && docker-compose up -d" 
  only:
    - nefertiti-development

deployNefStaging:
  stage: deployImage
  beforer_script:
    - echo ${NEF_STAGING_DOCKER_REGISTRY_PASSWORD} | docker login -u ${NEF_STAGING_DOCKER_REGISTRY_USER} ${NEF_STAGING_REGISTRY_URL} --password-stdin
  script:
    - docker tag ${REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_BRANCH} ${NEF_STAGING_DOCKER_REGISTRY_USER}/${IMAGE_NAME}:${CI_COMMIT_BRANCH}
    - docker push ${NEF_STAGING_DOCKER_REGISTRY_USER}/${IMAGE_NAME}:${CI_COMMIT_BRANCH}
    - kubectl annotate deployment/${DEPLOYMENT_NAME} restarted-at="$(date)" --overwrite
  only:
    - nefertiti-staging

deployNefStagingFailover:
  stage: deployImage
  beforer_script: 
    - echo ${NEF_STAGING_FAILOVER_KEY} > ~/${NEF_STAGING_FAILOVER_KEY}
    - chmod a+x ~/${NEF_STAGING_FAILOVER_KEY}
  script:
    - ssh -i ~/${NEF_STAGING_FAILOVER_KEY} ${NEF_STAGING_FAILOVER_IP} "cd /home/master/${CI_COMMIT_BRANCH}/ && docker-compose pull && docker-compose up -d" 
  only:
    - nefertiti-staging
